name: NodeSeek 自动签到评论加鸡腿

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # UTC 16:00，即北京时间 00:00

jobs:
  run-nodeseek-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # 使用最新版本的 checkout action
        uses: actions/checkout@v4

      - name: Set up Python
        # 使用最新版本的 setup-python action
        # 使用主版本号，避免特定补丁版本不存在的问题
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # 或者 '3.x'

      # 移除手动安装 chromium-browser, chromium-chromedriver, xvfb 的步骤。
      # undetected_chromedriver 会自动处理 ChromeDriver 的下载和匹配。
      # ubuntu-latest runner 通常已预装 Chromium。
      # xvfb 在使用 Chrome 的 --headless=new 模式时通常不需要。
      # - name: Install Chrome and Xvfb
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser chromium-chromedriver xvfb
      #     echo "Chrome version:"
      #     chromium-browser --version
      #     echo "ChromeDriver version:"
      #     chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # 先安装 requirements.txt 中的其他依赖
          pip install -r requirements.txt
          # 明确升级 undetected-chromedriver 和 selenium 到最新版本
          # 这是解决 Chrome/ChromeDriver 版本不匹配的关键步骤
          pip install -U undetected-chromedriver selenium

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          # NS_RANDOM 环境变量控制脚本行为，根据需要设置
          NS_RANDOM: ${{ secrets.NS_RANDOM }} # 或者直接设置为 "true" 或 "false"
          HEADLESS: "true" # 在 CI 环境中通常需要无头模式
        run: |
          # 运行你的 Python 脚本
          python nodeseek.py
